version: 2
jobs:
  test:
    working_directory: ~/librarian
    docker:
      - image: circleci/node:dubnium
      - image: ibmcom/cloudant-developer
      - image: redis
    environment:
      COUCH_PROTOCOL: 'http:'
      COUCH_HOST: localhost
      COUCH_PORT: 5984
      COUCH_ADMIN_USERNAME: admin
      COUCH_ADMIN_PASSWORD: pass
      COUCH_AUTH_DB: _users
      COUCH_LOG_DB: log
      DB_NAME: test-librarian
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      AWS_REGION: us-east-1
    steps:
      - checkout
      - run: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - restore_cache:
          keys:
            - v4-node_modules-{{ checksum "package-lock.json" }}
            - v4-node_modules-
      - run:
          command: npm install
          no_output_timeout: 5m
      - save_cache:
          key: v4-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
      - persist_to_workspace:
          root: ~/librarian
          paths: .

  publish:
    working_directory: ~/librarian
    docker:
      - image: circleci/node:dubnium
    steps:
      - attach_workspace:
          at: ~/librarian
      - run:
          name: Authenticate with registry
          command: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:  # required since `publish` has tag filters AND requires `test`
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
